Repository DTS-STN/Service-Canada-Design-System, pull requests merged in 2021-11, with the labels that each got.

#25 Ds 182/footer
  src/assets/facebook.svg
  src/assets/gc-logo.svg
  src/assets/instagram.svg
  src/assets/linkedin.svg
  src/assets/mobile-logo.svg
  src/assets/twitter.svg
  src/assets/up-arrow.svg
  src/assets/youtube.svg
  src/components/Footer/static/Footer.html
  src/components/Footer/static/footer.css
Labels: enhancement

#26 Ds 182 header html css
  src/assets/arrow-dwn-blk.svg
  src/assets/arrow-dwn-white.svg
  src/assets/arrow-up-blk.svg
  src/assets/search-icon.svg
  src/assets/sig-blk-en.svg
  src/components/Footer/static/footer.css
  src/components/Header/static/header.css
  src/components/Header/static/header.html
Labels: enhancement

#31 DS-106 linting
  .eslintrc
  README.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#30 Ds 105 adding release process to readme
  .storybook/preview.js
  CHANGELOG.md
  README.md
  src/components/ActionButton/ActionButton.js
  src/components/ActionButton/ActionButton.stories.js
  src/components/Banner/Banner.stories.js
  src/components/Breadcrumb/Breadcrumb.stories.js
  src/components/CallToAction/CallToAction.stories.js
  src/components/CheckBox/CheckBox.stories.js
  src/components/DateModified/DateModified.stories.js
  src/components/Details/Details.stories.js
  src/components/ErrorBox/ErrorBox.stories.js
  src/components/ErrorLabel/ErrorLabel.stories.js
  src/components/Experiment/Experiment.stories.js
  src/components/Filter/Filter.stories.js
  src/components/Footer/Footer.stories.js
  src/components/HTMList/HTMList.stories.js
  src/components/LayoutContainer/LayoutContainer.stories.js
  src/components/List/List.stories.js
  src/components/Menu/Menu.stories.js
  src/components/MultiTextField/MultiTextField.stories.js
  src/components/OptionalListField/OptionalListField.stories.js
  src/components/OptionalTextField/OptionalTextField.stories.js
  src/components/PhaseBanner/PhaseBanner.stories.js
  src/components/Quote/Quote.stories.js
  src/components/RadioButton/RadioButton.stories.js
  src/components/RadioField/RadioField.stories.js
  src/components/ReportAProblem/ReportAProblem.stories.js
  src/components/SearchBar/SearchBar.stories.js
  src/components/SelectField/SelectField.stories.js
  src/components/TextButtonFIeld/TextButtonField.stories.js
  src/components/TextField/TextField.stories.js
  src/index.js
Labels: documentation, enhancement

#32 Ds 80 adding licenses for oss
  LICENSE.md
  README.md
Labels: documentation

#33 Updating readme
  .github/pull_request_template.md
  README.md
Labels: documentation

#34 Ds 193/experiment footer
  .eslintrc
  CHANGELOG.md
  package-lock.json
  package.json
  rollup.config.js
  src/assets/bg-banner-mobile.png
  src/assets/bg-banner-v2.png
  src/assets/external-link.svg
  src/assets/wmms-blk.svg
  src/components/ActionButton/ActionButton.js
  src/components/DateModified/DateModified.js
  src/components/Details/Details.js
  src/components/Experiment/Experiment.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.stories.js
  src/components/Footer/Footer.test.js
  src/components/OptionalTextField/OptionalTextField.js
  src/components/ReportAProblem/ReportAProblem.js
  src/styles/globals.css
Labels: enhancement

#35 Ds 111 a012 grids responsive breakpoints
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/components/CallToAction/CallToAction.js
  src/components/Experiment/Experiment.js
  src/components/Experiment/Experiment.stories.js
  src/components/Experiment/Experiment.test.js
  src/components/Footer/Footer.js
  src/components/LayoutContainer/LayoutContainer.js
  src/components/LayoutContainer/LayoutContainer.stories.js
  src/components/LayoutContainer/LayoutContainer.test.js
  src/components/Menu/Menu.js
  src/components/PhaseBanner/PhaseBanner.js
  src/index.js
  src/styles/tailwind.css
  tailwind-bootstrap3.js
  tailwind-bootstrap5.js
  tailwind.config.js
Labels: enhancement

#39 Ds 111 fixing max content on bootstrap3 file
  src/styles/tailwind.css
  tailwind-bootstrap3.js
Labels: bug

#36 Ds 110/type
  .storybook/preview.js
  config-plugins/typography-plugin.js
  src/stories/styles/Typography/Typography.js
  src/stories/styles/Typography/Typography.stories.js
  src/styles/tailwind.css
  tailwind.config.js
Labels: documentation, enhancement

#41 Ds 134/design image folder
  .npmrc
  src/assets/wiki_images/README.md
Labels: documentation

#50 Ds 112/colour style
  .eslintrc
  src/components/ActionButton/ActionButton.js
  src/components/ActionButton/ActionButton.stories.js
  src/components/ActionButton/ActionButton.test.js
  src/components/TextButtonFIeld/TextButtonField.test.js
  src/stories/styles/Colors/Colors.js
  src/stories/styles/Colors/Colors.stories.js
  tailwind.config.js
Labels: documentation
