Repository DTS-STN/Service-Canada-Design-System, pull requests merged in 2021-12, with the labels that each got.

#54 added styling and documentaion for dividers
  CHANGELOG.md
  config-plugins/divider-plugin.js
  src/stories/styles/Dividers/Dividers.js
  src/stories/styles/Dividers/Dividers.stories.js
  src/stories/styles/Typography/Typography.stories.js
  tailwind.config.js
Labels: documentation, enhancement

#59 added missing font/style for display and updated docs
  config-plugins/typography-plugin.js
  src/stories/styles/Typography/Typography.stories.js
  src/styles/fonts.css
  tailwind.config.js
Labels: documentation

#74 Add Image Component
  .storybook/main.js
  CHANGELOG.md
  package-lock.json
  package.json
  src/assets/image1.png
  src/assets/image2.png
  src/components/Image/Image.js
  src/components/Image/Image.stories.js
  src/components/Image/Image.test.js
  tailwind.config.js
Labels: enhancement
