Repository DTS-STN/Service-Canada-Design-System, pull requests merged in 2022-01, with the labels that each got.

#69 Ds 150/buttons
  CHANGELOG.md
  config-plugins/button-plugin.js
  src/components/ActionButton/ActionButton.stories.js
  src/components/Button/Button.js
  src/components/Button/Button.stories.js
  src/components/Button/Button.test.js
  src/index.js
  tailwind.config.js
Labels: enhancement

#106 Ds 150/button fix
  src/components/Button/Button.js
  src/components/Button/Button.stories.js
  src/components/Image/Image.js
  src/components/Image/Image.test.js
Labels: bug

#72 Add Link Component
  CHANGELOG.md
  src/components/Link/Link.js
  src/components/Link/Link.stories.js
  src/components/Link/Link.test.js
  src/index.js
  tailwind.config.js
Labels: enhancement

#109 Ds 56/footer
  config-plugins/footer-plugin.js
  dts-stn-decd-design-system-1.0.0.tgz
  src/assets/arrow-up-blk.svg
  src/assets/up-arrow.svg
  src/assets/upArrow.svg
  src/components/Button/Button.js
  src/components/Button/Button.stories.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.stories.js
  src/components/Footer/Footer.test.js
  src/components/Link/Link.js
  src/components/Link/Link.test.js
  src/index.js
  src/translations/en.json
  src/translations/fr.json
  tailwind.config.js
Labels: enhancement

#112 Develop
  .eslintrc
  CHANGELOG.md
  config-plugins/errorpage-plugin.js
  config-plugins/footer-plugin.js
  dts-stn-decd-design-system-1.0.0.tgz
  src/assets/arrow-up-blk.svg
  src/assets/downArrow.svg
  src/assets/up-arrow.svg
  src/assets/upArrow.svg
  src/components/Button/Button.js
  src/components/Button/Button.stories.js
  src/components/ErrorPage/ErrorPage.js
  src/components/ErrorPage/ErrorPage.stories.js
  src/components/ErrorPage/ErrorPage.test.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.stories.js
  src/components/Footer/Footer.test.js
  src/components/Link/Link.js
  src/components/Link/Link.stories.js
  src/components/Link/Link.test.js
  src/index.js
  src/translations/en.json
  src/translations/fr.json
  tailwind.config.js
Labels: enhancement

#113 Release
  .eslintrc
  CHANGELOG.md
  config-plugins/errorpage-plugin.js
  config-plugins/footer-plugin.js
  dts-stn-decd-design-system-1.0.0.tgz
  package-lock.json
  package.json
  src/assets/arrow-up-blk.svg
  src/assets/downArrow.svg
  src/assets/up-arrow.svg
  src/assets/upArrow.svg
  src/components/Button/Button.js
  src/components/Button/Button.stories.js
  src/components/ErrorPage/ErrorPage.js
  src/components/ErrorPage/ErrorPage.stories.js
  src/components/ErrorPage/ErrorPage.test.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.stories.js
  src/components/Footer/Footer.test.js
  src/components/Link/Link.js
  src/components/Link/Link.stories.js
  src/components/Link/Link.test.js
  src/index.js
  src/translations/en.json
  src/translations/fr.json
  tailwind.config.js
Labels: enhancement

#114 Release
  CHANGELOG.md
  package.json
Labels: bug

#115 fixing deployment and publishing to main
  .github/workflows/build-and-deploy-storybooks.yml
  dts-stn-decd-design-system-1.0.0.tgz
  dts-stn-decd-design-system-1.0.3.tgz
  src/api/report-a-problem.js
  src/components/OptionalListField/OptionalListField.test.js
  src/components/OptionalTextField/OptionalTextField.test.js
  src/components/PhaseBanner/PhaseBanner.js
  src/components/PhaseBanner/PhaseBanner.stories.js
  src/components/PhaseBanner/PhaseBanner.test.js
  src/components/RadioField/RadioField.js
  src/components/RadioField/RadioField.stories.js
  src/components/RadioField/RadioField.test.js
  src/lib/notify/submitEmail.js
  src/lib/notify/submitEmail.test.js
Labels: bug

#116 still debugging D:
  CHANGELOG.md
Labels: bug

#119 deployment debugging removed release step
  .github/workflows/publish-package-on-release.yml
  .npmrc
  CHANGELOG.md
  package-lock.json
  package.json
Labels: bug

#121 Ds 202/messages
  .npmrc
  CHANGELOG.md
  config-plugins/message-plugin.js
  dts-stn-decd-design-system-1.0.7.tgz
  rollup.config.js
  src/assets/danger_img.svg
  src/assets/info_img.svg
  src/assets/success_img.svg
  src/assets/warning_img.svg
  src/components/Message/Message.js
  src/components/Message/Message.stories.js
  src/components/Message/Message.test.js
  src/index.js
  tailwind.config.js
Labels: enhancement

#123 updated readme instructions
  README.md
Labels: documentation
